---

#########################
# Tasks (Remote HAProxy Remove)
#########################

- name: HAProxy Removal Tasks
  block:

    - name: "{{ type }} HAProxy packages"
      package:
        name:
          - haproxy
        state: "{{ state }}"

    - name: Start Firewalld
      service:
        name: firewalld
        state: started
        enabled: True

    - name: "{{ type }} TCP Port 80 (HTTP)"
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: True
        state: disabled
      notify:
        - "Reload Firewalld"
        - "Restart Firewalld"

    - name: "{{ type }} TCP Port 443 (HTTPS)"
      ansible.posix.firewalld:
        port: 443/tcp
        permanent: True
        state: disabled
      notify:
        - "Reload Firewalld"
        - "Restart Firewalld"

    - name: "{{ type }} TCP Port 6443 (Kubernetes)"
      ansible.posix.firewalld:
        port: 6443/tcp
        permanent: True
        state: disabled
      notify:
        - "Reload Firewalld"
        - "Restart Firewalld"

    - name: "{{ type }} TCP Port 1936 (HAProxy Stats)"
      ansible.posix.firewalld:
        port: 1936/tcp
        permanent: True
        state: disabled
      notify:
        - "Reload Firewalld"
        - "Restart Firewalld"

    - name: "{{ type }} Kubernetes to use TCP port 6443"
      community.general.seport:
        ports: 6443
        proto: tcp
        reload: True
        setype: http_port_t
        state: "{{ state }}"

    - name: "{{ type }} HAProxy to use TCP port 1936"
      community.general.seport:
        ports: 1936
        proto: tcp
        reload: True
        setype: http_port_t
        state: "{{ state }}"

    - name: "{{ type }} HAProxy config"
      file:
        path: /etc/haproxy/haproxy.cfg
        state: "{{ state }}"

  when:
    - type is defined
    - type == "Remove"
    - state is defined
