---

#########################
# Repository (Create)
#########################

- name: Configure defined repositories
  block:

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/rpm_key_module.html
    - name: "{{ type }} GPG Key {{ repo.name }}"
      rpm_key:
        key: "{{ repo.gpgkey }}"
        fingerprint: "{{ repo.gpgfingerprint | default(omit) }}"
        state: "{{ state }}"
      when: repo.gpgkey is defined

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html
    - name: "{{ type }} RPM repository {{ repo.name }}"
      yum_repository:
        name: "{{ repo.name }}"
        file: "{{ repo.name }}"
        description: "{{ repo.description | default(repo.name) }}"
        baseurl: "{{ repo.baseurl }}"
        enabled: "{{ repo.enabled | default('true', true) }}"
        gpgcheck: "{{ repo.gpgcheck | default('false', true) }}"
        gpgkey: "{{ repo.gpgkey | default(omit) }}"
        state: "{{ state }}"

  become: true
  when:
    - ansible_facts.distribution == "RedHat"
      or ansible_facts.distribution == "CentOS"
      or ansible_facts.distribution == "Fedora"
  tags:
    - repository_create
