---

#########################
# Services
#########################

# If enabled, configures and enables services
crc_services: True

# User customizable services to enable
crc_services_enable_user: []
# - libvirtd
