---

#########################
# Tasks (Remote DNSMasq Remove)
#########################

- name: DNSMasq Removal Tasks
  block:

    - name: "{{ type }} DNSMasq packages"
      package:
        name:
          - dnsmasq
        state: "{{ state }}"

    - name: Start Firewalld
      service:
        name: firewalld
        state: started
        enabled: True

    - name: "{{ type }} TCP Port 53 (DNS)"
      ansible.posix.firewalld:
        port: 53/tcp
        permanent: True
        state: disabled
      notify:
        - "Reload Firewalld"
        - "Restart Firewalld"

    - name: "{{ type }} UDP Port 53 (DNS)"
      ansible.posix.firewalld:
        port: 53/udp
        permanent: True
        state: disabled
      notify:
        - "Reload Firewalld"
        - "Restart Firewalld"

    #- name: "{{ type }} DNSMasq to use TCP port 53"
    #  community.general.seport:
    #    ports: 53
    #    proto: tcp
    #    reload: True
    #    setype: dns_port_t
    #    state: "{{ state }}"

    #- name: "{{ type }} DNSMasq to use UDP port 53"
    #  community.general.seport:
    #    ports: 53
    #    proto: udp
    #    reload: True
    #    setype: dns_port_t
    #    state: "{{ state }}"

    - name: "{{ type }} NetworkManager config (CRC Server)"
      file:
        path: /etc/NetworkManager/conf.d/crc-dnsmasq.conf
        state: "{{ state }}"
      notify:
        - "Reload NetworkManager"

    - name: "{{ type }} DNSMasq config (CRC Server)"
      file:
        path: /etc/NetworkManager/dnsmasq.d/crc-dnsmasq.conf
        state: "{{ state }}"

    - name: "{{ type }} NetworkManager config (CRC Client)"
      file:
        path: /etc/NetworkManager/conf.d/crc-dnsmasq.conf
        state: "{{ state }}"
      delegate_to: localhost
      notify:
        - "Reload NetworkManager"

    - name: "{{ type }} DNSMasq config (CRC Client)"
      file:
        path: /etc/NetworkManager/dnsmasq.d/crc-dnsmasq.conf
        state: "{{ state }}"
      delegate_to: localhost

  when:
    - type is defined
    - type == "Remove"
    - state is defined
