---

#########################
# Information
#########################

- name: Display CRC Information
  block:

    - name: Get CRC server URL
      command:
        argv:
          - crc
          - console
          - --url
      become: False
      become_user: "{{ crc_server_user_crc }}"
      register: crc_server_console_url
      ignore_errors: True
      changed_when: False

    - name: Get CRC server credentials
      command:
        argv:
          - crc
          - console
          - --credentials
      become: False
      become_user: "{{ crc_server_user_crc }}"
      register: crc_server_console_creds
      ignore_errors: True
      changed_when: False

    - name: Show CRC server VM details
      command:
        argv:
          - virsh
          - -c
          - qemu:///system
          - list
          - --all
      register: crc_server_virsh
      become: True
      ignore_errors: True
      changed_when: False

    - name: Display CRC information
      debug:
        msg:
          - "#############################################"
          - "########### CodeReady Containers ############"
          - "#############################################"
          - " "
          - "Virtual Machine:"
          - " "
          - "{{ crc_server_virsh.stdout_lines | default('Error obtaining VM details') }}"
          - " "
          - "Console URL: {{ crc_server_console_url.stdout | default('Error obtaining URL') }}"
          - " "
          - "Troubleshooting: Run the following commands from the CRC host"
          - "     Debug Pod:"
          - "oc debug node/$(oc get nodes -o=jsonpath='{.items[0].metadata.name}')"
          - "     VM Shell:"
          - "ssh crc"
          - " "
          - "Credentials:"
          - " "
          - "{{ crc_server_console_creds.stdout_lines | default('Error obtaining credentials') }}"
          - " "

  when:
    - not ansible_check_mode
    - type is defined
    - type == "Install"
